### PR TITLE
Created comp2024 and added the field layout

### PR DESCRIPTION
**Pull request by zaraansari17**

### CODE REVIEW

**Review by jmullins16 — COMMENTED** [review]
Please remove Comp2023-imported-imported. It was already deleted by others, and somehow your branch is bringing it back.

When I showed you how to create the WPICreateProjectTest, it was only to go through the steps so you can see how it's done. I don't think we should keep that around on your branch.

**Review by jmullins16 — COMMENTED** [review]
Hoping to force my comments to show by submitting a review.

**Comment by hpark-24** [comment]
> Please remove Comp2023-imported-imported. It was already deleted by others, and somehow your branch is bringing it back.
> 
> When I showed you how to create the WPICreateProjectTest, it was only to go through the steps so you can see how it's done. I don't think we should keep that around on your branch.

I can't see the other comments but I finished removing Comp2023-Imported-Imported and removed some of the simgui.json files.

**Review by hpark-24 — DISMISSED** [review]
Looks good!

**Review by jmullins16 — APPROVED** [review]
Still some items to do in the CSP spreadsheet, but this needs to be merged and shared with everyone.

**Pull request merged**
